channels:
- ecpy
- defaults

dependencies:
- alabaster
- babel
- cairo
- configobj
- docutils
- argh
- atom
- enaml
- enaml-pygments
- kiwisolver
- pathtools
- watchdog
- fontconfig
- freetype
- future
- glib
- harfbuzz
- imagesize
- jinja2
- libffi
- libpng
- libxml2
- markupsafe
- mkl
- numpy
- openssl
- pango
- pip
- pixman
- ply
- py
- pygments
- pyqt=4.11
- pytest
- python=3.5
- pytz
- pyyaml
- qt=4.8
- readline
- setuptools
- sip
- six
- snowballstemmer
- sphinx
- sphinx_rtd_theme
- sqlite
- tk
- wheel
- xz
- yaml
- zlib
